# Generated by Django 6.0.6 on 2026-06-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('contenido_html', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='correos.campana')),
            ],
        ),
    ]
