# Generated by Django 6.0.6 on 2026-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviocorreo',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='campana',
            name='contenido_html',
        ),
        migrations.RemoveField(
            model_name='campana',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='campana',
            name='contenido',
            field=models.TextField(default='Escribe tu mensaje aquí...', verbose_name='Contenido del mensaje (Texto o HTML)'),
        ),
        migrations.AddField(
            model_name='campana',
            name='nombre',
            field=models.CharField(default='Campaña Inicial', max_length=200, verbose_name='Nombre de la campaña (Uso interno)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana',
            name='asunto',
            field=models.CharField(default='¡Boletín Informativo!', max_length=250, verbose_name='Asunto del correo'),
        ),
    ]
