# Generated by Django 6.0.6 on 2026-06-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0002_alter_enviocorreo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enviocorreo',
            table='correos_enviocorreo',
        ),
    ]
